### ISSUE TITLE
Reader isn't working after page reload

### ISSUE THREAD

**Issue by tristandb** [JodusNodus/react-qr-reader#18]
After accepting usuage of my camera in Google Chrome on my desktop, the QR-code recognizing does work.
However, after reloading the page, recognizing QR-codes stops.
The application only works correctly on localhost

**Comment by JodusNodus** [comment]
**"However, after reloading the page, recognizing QR-codes stops."**
Does the preview display anything? Are there any errors thrown?
Does the problem occur on the [demo](https://jodusnodus.github.io/react-qr-reader/)?
I have tested it with the latest version of Chrome on macOs and it works great without any issues (even after page reloads).

**"The application only works correctly on localhost"**
If it only worked on localhost the problem is likely that you aren’t using https and it is required in most browsers (when not localhost) to use media devices. I might need to put a disclaimer in the docs about that.

**Comment by tristandb** [comment]
The problem doesn't occur when using the demo with my laptop. However, my mobile (Android 6.0.1, Chrome 56) doesn't seem to recognize qr codes, even with the demo. No errors are thrown.

For the application testing on an external server, I've already added an SSL-certificate.

**Comment by JodusNodus** [comment]
Have you tried using remote developer tools to debug it? I cannot seem to reproduce your problem. The speed of recognition can be slow because of the heavy nature of the algorithm but after a couple of seconds it's usually successfully recognised on my devices when the QR code itself is well captured.

**Comment by JodusNodus** [comment]
Thanks to @rbright i might have been able to solve your issue in version 1.0.3. Please update and let me know if it worked.

**Comment by tristandb** [comment]
Sorry for the late response, but the issue is solved in 1.0.3. Thanks for your support!
