### ISSUE TITLE
Cannot get to work on IOS Chrome with legacyMode={true}

### ISSUE THREAD

**Issue by twiz911** [JodusNodus/react-qr-reader#29]
Hi

I tried enabling legacyMode = {true} on IOS Chrome browser. This causes the camera component to render differently to a play logo but the camera's view does not appear. 

Any ideas how I can debug what's going wrong?

Many thanks

**Comment by JodusNodus** [comment]
So this issue is only present in IOS chrome? 

When legacyMode is enabled there should be no camera components. As you can see in the legacyMode example you need to provide your own button to trigger the image upload.

Check out the demo, when the browser doesn't support camera access it switches to legacyMode. So if you test the demo out in IOS chrome does the same problem arise?

Could you post an image of this?
