### ISSUE TITLE
Cannot read property srcObject of undefined

### ISSUE THREAD

**Issue by nicklasfrahm** [JodusNodus/react-qr-reader#47]
First of all, thank you for this awesome library. I just wanted to point to a minor bug, which does not affect functionality but should easily be fixed.

![console error](https://user-images.githubusercontent.com/20382326/33166179-9fbb63f8-d039-11e7-9ef2-2d55f2282661.png)

My code looks like this:

```javascript
import React from 'react'
import QrReader from 'react-qr-reader'

class AddPermission extends React.Component {
  constructor() {
    super()
    this.state = {
      delay: 300,
      result: 'No result'
    }
    this.handleScan = this.handleScan.bind(this)
  }
  handleScan(data) {
    if (data) {
      this.setState({
        result: data
      })
    }
  }
  handleError(err) {
    console.error(err)
  }
  render() {
    return (
      <div>
        <QrReader
          delay={this.state.delay}
          onScan={this.handleScan}
          onError={this.handleError}
          style={{ maxWidth: '300px', width: '100%' }}
          showViewFinder={false}
        />
        <p>{this.state.result}</p>
      </div>
    )
  }
}

export default AddPermission
```

The weird thing is just that this does not happen in your storybook.

**Comment by frinko** [comment]
@nicklasfrahm, what happens if you bind the handleError in the constructor?

**Comment by nicklasfrahm** [comment]
@frinko I just checked it and it didn't remove the error. It shouldn't make any difference though as the `this` context is not used inside that method.

**Comment by JodusNodus** [comment]
It seems that creating the reference has failed as the error says the preview property is `null` and not `undefined`. I have never come across this issue myself sadly. It's weird that after failing at that it continues and works after all. The PR doesn't fix the underlying problem here. Could you try to wrap the `componentDidMount` code with:
```js
setTimeout(() => {
  requestAnimationFrame(() => {
    // Code here
  })
}, 0)
```

Maybe the problem is that the component hasn't fully rendered and thus hasn't called the reference setter function.
