### ISSUE TITLE
Different height & width

### ISSUE THREAD

**Issue by fridezlucas** [JodusNodus/react-qr-reader#53]
Is it possible to implement the possibility to set a different height & width ?

After that, the camera will take all the screen but the QR Reader will be only in a square in the middle of it ?

**Comment by fridezlucas** [comment]
Yeah, but without the ratio 1:1 ?

**Comment by JodusNodus** [comment]
No sorry since version 2 it has to be 1:1. I chose this because it made it easier for styling across screens, camera resolutions, orientations, etc. It also speeds up the algorithm. This module was made to be very easy to use and batteries included. If you need a lot of customisability i recommend you check out one of the other options available.

**Comment by thenameisblanche** [comment]
Hello, may I ask how do I set the ratio to 1:1? because what I have is 3:4 as default and I tried to style it, change the container size, but it doesn't seem to fit. :<
