### ISSUE TITLE
Demo works but the same code does not work from my website on phone

### ISSUE THREAD

**Issue by kartik2014** [JodusNodus/react-qr-reader#83]
Hi @JodusNodus , great library first of all !

It works great when I work on my local in mac . But when I deploy it (my site is on http) and test it from my phone, it cannot access the camera. Could you please help with this?

I am using iphone ios 11.2.6

<QrReader
  onScan={this.handleScan}
 onError={this.handleError}
/>

**Comment by crenardy** [comment]
Hi @kartik2014 ,
that's not possible due to the nature of getUserMedia() and camera access which needs a secure context. More on that [here](https://w3c.github.io/webappsec-secure-contexts/).
Does your site really needs to be http?
You can always go for a let's encrypt certificate with the certbot or [ZeroSSL](https://zerossl.com/free-ssl/#crt).
